### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kumar-jayant** [eaxlex/OpenCart-4#1]
How can I Install these extensions on opencart as OC supports ".ocmod" file and these are ".zip" type file?

**Comment by eaxlex** [comment]
Hello Kumar,

When you try to upload the extension you need to change the format to "All Files".

It should work excellently in OC 4

<img width="501" alt="Screenshot 2023-01-13 at 12 32 44" src="https://user-images.githubusercontent.com/119623549/212300136-5d2885cc-aa9d-470c-a161-546980c1db57.png">

To:

<img width="524" alt="Screenshot 2023-01-13 at 12 35 04" src="https://user-images.githubusercontent.com/119623549/212299940-9f61b7e0-a274-48f0-893d-4c3cf4bb6d7f.png">
